# Generated by Django 4.1 on 2022-12-12 21:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cragName', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Wall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wallName', models.CharField(max_length=50)),
                ('crag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Climbing.crag')),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('routeName', models.CharField(max_length=50)),
                ('comments', models.CharField(max_length=3000)),
                ('description', models.CharField(max_length=100)),
                ('wall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Climbing.wall')),
            ],
        ),
    ]
